# Generated by Django 4.2.30 on 2026-06-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_merchant_name',
            field=models.CharField(blank=True, help_text='Extracted or configured merchant name for the UPI QR.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_qr_code',
            field=models.ImageField(blank=True, help_text='Auto-generated clean QR Code based on the UPI ID.', null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_upi_id',
            field=models.CharField(blank=True, help_text='Configured UPI ID for receiving payments.', max_length=100, null=True),
        ),
    ]
